web:
  image: berpj/web-demo
  ports:
    - "80:80"
  environment:
    API_URL: http://192.168.99.100:3000
app:
  image: berpj/app-demo
  ports:
    - "3000:3000"
  environment:
    RAILS_ENV: production
    DB_HOST: 192.168.99.100
    DB_PORT: 5432
    DB_ADAPTER: postgresql
    DB_DATABASE: todo
    DB_USER: todo
    DB_PASS: mypass
db:
  image: macadmins/postgres
  volumes_from:
    - dbdata
  ports:
    - "5432:5432"
  environment:
    DB_NAME: todo
    DB_USER: todo
    DB_PASS: mypass
dbdata:
  image: busybox
  command: /bin/sh
  volumes:
    - /etc/postgresql
    - /var/log/postgresql
    - /var/lib/postgresql
